package org.myapplication.common.api.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.io.Serializable;
import java.util.UUID;
import org.hibernate.annotations.UuidGenerator;

/**
 * A base entity class with an auto-generated UUID ID.
 */
@MappedSuperclass
public class AutoGeneratedUUIDIdBaseEntity implements Serializable {

  @Id
  @Column(name = "id", nullable = false)
  @GeneratedValue(generator = "UUID")
  @UuidGenerator
  private UUID id;

  public UUID getId() {
    return id;
  }

  public AutoGeneratedUUIDIdBaseEntity setId(UUID id) {
    this.id = id;
    return this;
  }
}
