apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/keycloak/realms/
              readOnly: true
            - name: keycloak-scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm
        - name: keycloak-scripts
          configMap:
            name: keycloak-scripts
