apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: keycloak-realm
    files:
      - master-realm.json
  - name: keycloak-scripts
    files:
      - start-keycloak.sh
resources:
  - keycloak-deployment.yaml
patches:
  - path: keycloak-volume-patch.yaml
    target:
      kind: Deployment
      name: keycloak
